import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const Girloy = localFont({
  src: [
    {
      path: './fonts/Girloy-Bold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/Girloy-Heavy.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/Girloy-Light.ttf',
      weight: '200',
      style: 'normal',
    },
    {
      path: './fonts/Girloy-Medium.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/Girloy-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Girloy.className} antialiased bg-slate-100`}
      >
        {children}
      </body>
    </html>
  );
}
